GET http://127.0.0.1:8000/api/player
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTkxNjUyNjYsImV4cCI6MTYxOTE2ODg2Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9obi5kb2UxMWExMTExMjFhMyJ9.URxeOONIA7pilfOvsupc2CrrftpJCAouaFTriqf-Oz2rKevMxZ-z0HArUhfqM-LSIKEgIdYjSED5-2Fq_qb4RTrBBMk_6SsZ3djjJ8blu3kxtVONoSWpMl7WJEiGebI2Mkjv6LqCGfA7Lh5yyj94pJHFmWGDGXXtARESjj9ExABJHACDOrcQp8rTyDkTDPDslRde7q4sbmZB-YZA4soBszObGaLo6-_cp3ueRwGDWgGC8-BXFpZ7fwf37EV1io_YQvGgx91iNMDpwQdQZliLwGaJfaIgWZ4zOE5xy9GxaR5-DR4jBNw80gkyd_qOCj-kzJX0QYf2Pc_fcJskERYA81C_6gkkOMli-u6Y9YI3c9S1LhKToXFQHUaockgLtFAnWECUyFmjpf4XvAZIQNRGEvzwYPbWli0YUVY3h-xGuQM4HWubFZMaGTrzu-yF2NIXDBqCJGVZAjtFRzF_sZWnZy6DDzRYj24NflbPih2om-qiH7UeR28214UbB5x5LMd25Tuj4NXA-qoP8gOdNkbQWv-nsjWKvziATOngk4WG8ByG6Vuz-Yu_NEi1Yt7qsw3TvRXGG3ZFe1BOqU7yYlN8xaVKq2QtZZtt5o8-Pvz3zfayasS1bW7snv6ufOAPKsgfIoaQyol3iASYpJumXTVLUZsMU9diNIowqzGI6YHQRDA

###

PUT http://127.0.0.1:8000/api/player/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTkxNjUyNjYsImV4cCI6MTYxOTE2ODg2Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9obi5kb2UxMWExMTExMjFhMyJ9.URxeOONIA7pilfOvsupc2CrrftpJCAouaFTriqf-Oz2rKevMxZ-z0HArUhfqM-LSIKEgIdYjSED5-2Fq_qb4RTrBBMk_6SsZ3djjJ8blu3kxtVONoSWpMl7WJEiGebI2Mkjv6LqCGfA7Lh5yyj94pJHFmWGDGXXtARESjj9ExABJHACDOrcQp8rTyDkTDPDslRde7q4sbmZB-YZA4soBszObGaLo6-_cp3ueRwGDWgGC8-BXFpZ7fwf37EV1io_YQvGgx91iNMDpwQdQZliLwGaJfaIgWZ4zOE5xy9GxaR5-DR4jBNw80gkyd_qOCj-kzJX0QYf2Pc_fcJskERYA81C_6gkkOMli-u6Y9YI3c9S1LhKToXFQHUaockgLtFAnWECUyFmjpf4XvAZIQNRGEvzwYPbWli0YUVY3h-xGuQM4HWubFZMaGTrzu-yF2NIXDBqCJGVZAjtFRzF_sZWnZy6DDzRYj24NflbPih2om-qiH7UeR28214UbB5x5LMd25Tuj4NXA-qoP8gOdNkbQWv-nsjWKvziATOngk4WG8ByG6Vuz-Yu_NEi1Yt7qsw3TvRXGG3ZFe1BOqU7yYlN8xaVKq2QtZZtt5o8-Pvz3zfayasS1bW7snv6ufOAPKsgfIoaQyol3iASYpJumXTVLUZsMU9diNIowqzGI6YHQRDA

{
    "username":"jonkata",
    "email":"jonkata@gmail.com",
    "avatar":"www.zandaria.com",
}

###

GET http://127.0.0.1:8000/api/team
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTkxNjUyNjYsImV4cCI6MTYxOTE2ODg2Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9obi5kb2UxMWExMTExMjFhMyJ9.URxeOONIA7pilfOvsupc2CrrftpJCAouaFTriqf-Oz2rKevMxZ-z0HArUhfqM-LSIKEgIdYjSED5-2Fq_qb4RTrBBMk_6SsZ3djjJ8blu3kxtVONoSWpMl7WJEiGebI2Mkjv6LqCGfA7Lh5yyj94pJHFmWGDGXXtARESjj9ExABJHACDOrcQp8rTyDkTDPDslRde7q4sbmZB-YZA4soBszObGaLo6-_cp3ueRwGDWgGC8-BXFpZ7fwf37EV1io_YQvGgx91iNMDpwQdQZliLwGaJfaIgWZ4zOE5xy9GxaR5-DR4jBNw80gkyd_qOCj-kzJX0QYf2Pc_fcJskERYA81C_6gkkOMli-u6Y9YI3c9S1LhKToXFQHUaockgLtFAnWECUyFmjpf4XvAZIQNRGEvzwYPbWli0YUVY3h-xGuQM4HWubFZMaGTrzu-yF2NIXDBqCJGVZAjtFRzF_sZWnZy6DDzRYj24NflbPih2om-qiH7UeR28214UbB5x5LMd25Tuj4NXA-qoP8gOdNkbQWv-nsjWKvziATOngk4WG8ByG6Vuz-Yu_NEi1Yt7qsw3TvRXGG3ZFe1BOqU7yYlN8xaVKq2QtZZtt5o8-Pvz3zfayasS1bW7snv6ufOAPKsgfIoaQyol3iASYpJumXTVLUZsMU9diNIowqzGI6YHQRDA


#POST http://127.0.0.1:8000/register
#Accept: application/json
#Content-Type: application/json
#
#{
#  "first_name": "Enes",
#  "last_name": "Karadzhov",
#  "email": "enes.karadzhov@gmail.com",
#  "username": "qwertrewqwertrewq",
#  "password": "qwertyuytrewe",
#  "posts": {
#    "content": "dadadada"
#  }
#}